### PR TITLE
Adding support for Windows - Fixed compilation issues

### PR DESCRIPTION
**Pull request by sriniprash**
Fixed the following in code.google.com/p/codesearch/index package
1) Fixed a few compilation issues in mmap_windows.go (caused due to older api version of syscall pakage).
2) Created platform specific versions of read.go and write.go with minor changes.

Tested the resultant build. Working fine on windows.

### CODE REVIEW

**Comment by jklein** [comment]
I don't love this solution, because now there is a ton of duplication in the platform specific read/write files. Can you [DRY](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself) this out?

**Comment by sriniprash** [comment]
Yep. Makes sense! Will try to reduce the amount of duplication and separate out only the bare minimum platform specific code out.

**Comment by jklein** [comment]
I'm going to close this to keep the queue clean, feel free to open a new PR once you have modified your changes.

**Comment by sriniprash** [comment]
Created a new PR for this - #56

**Pull request closed without merging**
