### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by reinhardt1053**
Cloning the project using https

### CODE REVIEW

**Comment by jklein** [comment]
Why is this a change that's worth making? If people want to clone it with HTTPS it's easy enough to do from the GitHub UI.

**Comment by reinhardt1053** [comment]
Well, people not familiar with git that will follow your step-by-step instructions will get an error.

**Comment by jklein** [comment]
Because windows doesn't support SSH style URLs? Sorry I'm just trying to figure out when the error occurs.

**Comment by reinhardt1053** [comment]
screen shot 2015-02-02 at 16 03 21

**Comment by reinhardt1053** [comment]
From Github official doc: 
https://help.github.com/articles/which-remote-url-should-i-use/

"Cloning with SSH

These URLs provide access to a Git repository via SSH, which is a secure protocol. To use these URLs, you must have an SSH keypair generated on your computer, and attached to your GitHub account."

**Comment by jklein** [comment]
Ah okay, got it. Can you just change the other instance in the README as well in that case? I'm happy to merge, but this line appears twice now.

**Comment by reinhardt1053** [comment]
Ok, I am gonna do that :+1:

**Pull request merged**
