### PR TITLE
Introduce support for GitHub wiki search

### PR DESCRIPTION
**Pull request by miketheman**
Simplistic approach in supporting GitHub wiki via frontend replacements
of paths.

Requires a non-default `url-pattern/base-url` in configuration file.

Refs #150 

I thought about going one step further and having the default use case detect if the url passed is a wiki or not, but that seemed to go deeper into changing [this code](https://github.com/miketheman/hound/blob/95306e06a49c8459d5ab372ebcc8bd79707a484c/config/config.go#L104-L112) and it seemed like keeping the change simple was a better approach.

### CODE REVIEW

**Comment by miketheman** [comment]
Tagging @kellegous, who is apparently the holder of merges here.

**Comment by kellegous** [comment]
This seems reasonable. I hope to clean up this URL munging on the client-side sometime in the future. I'm going to try this out soon and then I'll get it merged.

**Comment by avleen** [comment]
Tried it out, seems to work without breaking anything. Will merge as it seems pretty useful!

**Comment by kellegous** [comment]
Thanks @avleen, I forgot to merge this.

**Comment by avleen** [comment]
No problem @kellegous! Got your back, you've been busy :-)

**Pull request merged**
