### PR TITLE
Support bazaar's repositories + use json's repo's section name as name

### PR DESCRIPTION
**Pull request by massix**
Similar to #63 with the only exception that the name that will be shown in the HTML interface will be the one used in the .json file.

### CODE REVIEW

**Comment by jklein** [comment]
LGTM @massix, thanks. It is going to change the UI for pretty much everyone since we are changing the way we display repos, but I think this will be fine. For most people I think the name in the config matches the repo name anyway. 

@kellegous - take a look and merge when ready.

**Comment by kellegous** [comment]
@massix Can you recommend a public bzr repo to try this out on?

**Comment by massix** [comment]
Hi @kellegous , I am sorry but I'm not masochist enough to use bazaar outside of the working environment, therefore I don't know any public repository :disappointed: 

That said, I think that Canonical's Launchpad hosts some bzr repo, but I'm not sure.

**Comment by belak** [comment]
http://en.wikipedia.org/wiki/GNU_Bazaar#Projects_using_Bazaar

lp:beautifulsoup looks promising.

**Comment by jklein** [comment]
@massix sorry for the delay on this, want to fix the conflict and we'll take another look and hopefully merge soon?

**Comment by kellegous** [comment]
@massix See if there is anything else I need to add in #89.

**Comment by massix** [comment]
Best regards,
Massimo Gengarelli
M: +33 (0)6 43 87 57 67

**Pull request closed without merging**
