### PR TITLE
Add tool to seed a config.json file with all repositories owned by an org

### PR DESCRIPTION
**Pull request by f2prateek**
Also adds `omitempty` to struct tags in `config.Repo` so the generated json is compact.

### CODE REVIEW

**Comment by f2prateek** [comment]
Figured it would help people getting started. 

Feel free to close if this isn't something to added to Hound itself (it probably isn't).

**Comment by sstarcher** [comment]
Yes please

**Comment by sstarcher** [comment]
@f2prateek I went ahead and took what you started and made it supported by the config.json along with adding bitbucket support

https://github.com/sstarcher/hound

**Comment by sstarcher** [comment]
Any chance we could get this merged?

**Comment by shimont** [comment]
I would love to use have this feature

**Pull request closed without merging**
