### PR TITLE
Moves "manifests" into the index package.

### PR DESCRIPTION
**Pull request by kellegous**
- Removes index.Snapshot
- Creates index.IndexRef that is responsible for index metadata.

### CODE REVIEW

**Comment by kellegous** [comment]
TODO:
- Tests on index resurrection.
- Tests on index removal.

**Comment by kellegous** [comment]
This just better encapsulates the notion of manifests within the Index, instead of the searcher. I realized this was way cleaner when I landed that last PR. Now I'm going to focus on getting the various VCS additions landed.

**Comment by jklein** [comment]
Looks good @kellegous, and I like that we are starting to have tests. At some point we should probably add TravisCI - it's free for open source projects.

**Comment by kellegous** [comment]
Oh good idea. I should have set that up earlier. We do have a number of tests buried in the index code.

**Pull request closed without merging**
